apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp-sync
  name: myapp-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-sync
  template:
    metadata:
      labels:
        app: myapp-sync
    spec:
      containers:
      - image: nginx:1.25.2
        name: myapp-sync
        ports:
        - containerPort: 80
        resources: {}
