apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app: mysite
  name: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - image: nginx:1.25.2
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
