apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  labels:
    app: newapp
  name: newapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
      - image: nginx:1.25.2
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
